# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Unknown Bit
tagline:             '-- python, web, bots, data/ai, blockchain'
description:         'I write on programming subjects. With interest in python, web, bots, data/ai and blockchain tech. Find me on twitter <a href="https://twitter.com/expl00ra" target="_blank">@expl00ra</a>.'
url:                 https://expl00ra.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Kofi Amanfo II
  url:               https://twitter.com/expl00ra
  email:             expl00ra@protonmail.com

# Custom vars
version:             1.0.0
